### ISSUE TITLE
Azure DevOps Generator Error with GitHub

### ISSUE THREAD

**Issue by andrehe001** [microsoft/AzureDevOpsDemoGenerator#387] opened 2021-02-23 09:34 UTC
I'm getting following error when using a MS Learn Template (Create a release pipeline with Azure Pipelines):

Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.

[AB#3603](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3603)

**Comment by briangre** [comment] 2021-05-19 15:30
Was there ever a resolution to this? I'm seeing this same error..

**Comment by aksh-h** [comment] 2021-05-21 04:52
Hello, @briangre Thank you for reaching us.

Please check whether you have permission to create service endpoints in the selected organization? If not please reach out to the organization owner or the project collection administrator.

Thanks

**Comment by briangre** [comment] 2021-05-21 12:06
I am the owner of the organization so I assume I do have those rights. Is it possibly a problem with conflicting credentials? My credentials in github are not the same as the devops organzation I'm using.

**Comment by aksh-h** [comment] 2021-05-27 03:24
This looks really strange. Could you please try it in a different organization? 
GitHub and Azure DevOps credentials should not be a problem as we are authenticating it seperately.

Please write an [email](mailto:akshay.hosur@ecanarys.com) if you face the same problem.

Thank you!!

**Comment by briangre** [comment] 2021-05-27 11:50
I created a new organization and received the same error message:

Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aksh-h** [comment] 2021-06-16 11:24
We duly apologize for the inconvenience caused. We could not reproduce this behavior even after creating a new organization and a brand new GitHub account. We don't have any other reports on this kind of issue.

**Comment by aksh-h** [comment] 2021-06-16 11:27
As per the policy, we can't keep this issue for long. Currently, I'm closing this thread. If the issue persists, please create a new thread with links to this issue.

Thanks!!

**Closed by aksh-h** 2021-06-16 11:27 UTC

**Comment by gbelenky** [comment] 2021-07-05 15:35
I have the same issue here
