### ISSUE TITLE
PartsUnlimited project is created with an empty repo

### ISSUE THREAD

**Issue by mkennten** [microsoft/AzureDevOpsDemoGenerator#407] opened 2021-03-25 10:15 UTC
Since this week we have more and more occurrences in which the creation of a project using the "PartsUnlimited" template is successful but doesn't have the repository imported/created. It's apparently not happening all the time, but when I tried it just now it did not import the repo.

[AB#3631](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3631)

**Comment by aksh-h** [comment] 2021-03-25 10:44
Hi @mkennten, Thank you for reaching us, could you please try it in production [site](https://azuredevopsdemogenerator.azurewebsites.net/)

**Comment by mkennten** [comment] 2021-03-25 10:58
I was using this site before and after clicking on "Sign in" got automatically re-directed to https://azuredevopsdemogenerator-core.azurewebsites.net. Now that you provided that link it did not redirect me and the import worked successfully. Did you change something already? Can we use the URL without being re-directed?

**Comment by aksh-h** [comment] 2021-03-25 11:04
We are migrating the application to Asp.Net Core and doing beta test with real-time user traffic https://azuredevopsdemogenerator-core.azurewebsites.net

But we didn't find any issue with importing repo for PartsUnlimited template. Could you please try again and let us know if the issue persists.

Thanks.

**Comment by mkennten** [comment] 2021-03-25 11:24
I tested the -core link again and the repo is still NOT imported (don't receive the mail, files are not there). It works with the production site, not with the -core one. And btw. it takes much longer using the -core site (up to 8 min) than the production site (2-4 min).

**Comment by aksh-h** [comment] 2021-03-25 11:31
Is it happening only for PartsUnlimited template? Could you please try the SmartHotel360 template as well, if not working we will assign this ticket to the team.

**Comment by mkennten** [comment] 2021-03-25 11:32
No, I just learnt that it happens also for a number of students (10%) for other template, e.g. Whitesource lab

**Comment by aksh-h** [comment] 2021-03-25 11:38
Thanks for more info. We will look into this.

**Comment by mkennten** [comment] 2021-03-25 11:41
Just tested SmartHotel360, same issue, no repo imported. It looks like the -core site only causes this issue.

**Comment by mkennten** [comment] 2021-03-26 13:41
For a while it looked like no forwarding to the -core site happened and everything seemed okay, but now I learnt from peers that they got forwarded and then the repo import still fails. In this case for the AKS template. What's the status?

**Comment by aksh-h** [comment] 2021-04-01 09:22
Could you please verify the repo import is working in https://azuredevopsdemogenerator-core.azurewebsites.net/ ??

**Comment by dmckinstry** [comment] 2021-04-01 15:08
@mkennten - Status update... @aksh-h is actively working on this...  The -core site appears to currently be offline with production traffic going through the stable "legacy" deployment.  But we are working on determining the issues with the -core implementation and fixing them.  Thank you!

**Comment by aksh-h** [comment] 2021-04-05 12:23
The issue has been resolved. Root cause for this issue was the configuration setting were wrongly updated.
Closing the issue.

**Closed by aksh-h** 2021-04-05 12:23 UTC

**Comment by mkennten** [comment] 2021-04-06 10:14
Just tested it, it works as expected, repo is imported. Thanks!
