### ISSUE TITLE
sign in demo doesn't work

### ISSUE THREAD

**Issue by replyxf** [microsoft/AzureDevOpsDemoGenerator#328] opened 2020-09-09 17:06 UTC
![image](https://user-images.githubusercontent.com/1699453/92629999-fd263a80-f283-11ea-9320-3ee2e82105dd.png)
first time I can sign it, I clicked template, then I clicked back button, then I can't log in

**Comment by replyxf** [comment] 2020-09-09 19:37
can you please restart the service asap, I need to use the demo generator for the training tomorrow.

**Comment by aksh-h** [comment] 2020-09-09 21:29
Hi @replyxf 
Thank you for reaching us. Please share the error messages you're recieving after clicking back button.

We don't have any restrictions on the usage of Demo Generator, you can use any number of times.
Could you please try it in incognito mode or any other browser? Let us know your comment below.

Thanks

**Comment by replyxf** [comment] 2020-09-09 22:33
There is no error message. I have tried  incognito mode or any other
browser, and another machine. Same problem. After I click sign it, it
returns the sign in page. My info must be cached in the server.  Can you
restart your service or check your server log, my alias is xizhao? Can you
please fix it ASAP?
thanks,

Chris

**Comment by aksh-h** [comment] 2020-09-10 02:46
We understand your concern. Can you try to login with any other email Id? It looks like it unable to retrive the profile or any other information from the logged in id.

**Comment by replyxf** [comment] 2020-09-10 03:20
I have logged in with my personal id chris.c.zhao. it is fine

**Comment by aksh-h** [comment] 2020-09-10 03:24
yes, could be an issue with Id itself not the application.

**Comment by replyxf** [comment] 2020-09-10 03:28
no, id is fine. I logged in successfully for the first time. Then, I click
the template and back button on the brower, then I can't log in and no
error message. something is wrong for your service.
https://azuredevopsdemogenerator.azurewebsites.net/?TemplateId=77377&Name=ContosoShuttle
Is this url correct? can you restart your service to mitigate this issue?

**Comment by aksh-h** [comment] 2020-09-10 03:34
The URL is correct, currently we unable to reproduce the issue. If you are available on teams we can connect and see.

**Comment by replyxf** [comment] 2020-09-10 03:42
from incognito, after I clicked sign in, I type my id/password, it went to
https://app.vssps.visualstudio.com/_signin?realm=app.vssps.visualstudio.com
..

return back to sign in window
https://azuredevopsdemogenerator.azurewebsites.net/Account/Verify  no error
message.

sometimes has the error 500 - Something went wrong!
We’ve encountered an error and cannot fulfill this request. We will trace
the error and get a fix out soon.
9/10/2020 3:34:02 AM (UTC)
8bdef839-875c-418f-bb04-acdaf5fc4051

eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2

**Comment by replyxf** [comment] 2020-09-10 03:43
I am at east coast, can you please check you log with my id redmond/xizhao,
can you please restart your service?

**Comment by aksh-h** [comment] 2020-09-10 03:52
is it possible to connect over a call and showcase your issue?use this [email](mailto:akshay.hosur@ecanarys.com) if you are on Microsoft teams or we shall try it with Google Meet.

**Comment by replyxf** [comment] 2020-09-10 04:02
too late for me.  why return back to sign in window
https://azuredevopsdemogenerator.azurewebsites.net/Account/Verify ? can you
please check aad log, I saw aad log in in url.
thanks,

**Comment by replyxf** [comment] 2020-09-10 04:03
who can I contact tomorrow morning for this issue?

**Comment by aksh-h** [comment] 2020-09-10 04:05
I'm ready to assist you anytime. Please try to spend sometime over the teams and help me to understand the issue.

**Comment by aksh-h** [comment] 2020-09-10 05:04
Please login to [staging](http://azuredevopsdemogenerator-staging.azurewebsites.net/) environment to see if the issue is from application or with the login.

**Comment by aksh-h** [comment] 2020-09-10 14:27
We tried to reproduce this offline, but due to security or any other reasons we could see issue with the sign in/authentication, often we encountered with status code 500. This is the reason used unable to login to demo generator. 

User(s) are able to create project and proceed with training. Hence closing the issue.

**Closed by aksh-h** 2020-09-10 14:27 UTC
