### ISSUE TITLE
Template extractor cannot export release pipeline

### ISSUE THREAD

**Issue by zhjuve** [microsoft/AzureDevOpsDemoGenerator#270] opened 2020-05-28 15:35 UTC
Hello, i get following error when exporting
Object reference not set to an instance of an object. at VstsDemoBuilder.Services.ExtractorService.<>c__DisplayClass30_2.b__2(KeyValuePair`2 x) in D:\a\1\s\src\VstsDemoBuilder\Services\ExtractorService.cs:line 1250 at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source) at VstsDemoBuilder.Services.ExtractorService.GeneralizingGetReleaseDefinitions(ProjectConfigurations appConfig) in D:\a\1\s\src\VstsDemoBuilder\Services\ExtractorService.cs:line 1250

What can be the root cause?

**Comment by aksh-h** [comment] 2020-06-01 14:56
Hi @zhjuve Thank you for reaching us. We will look into this.

**Comment by aksh-h** [comment] 2020-06-10 05:04
This could be related to unexpected Json format. We have generalized the logic to export different kinds pipeline definitions. This was an unexpected and we couldn't reproduce. Will make a note of this and closing the issue.

**Closed by aksh-h** 2020-06-10 05:04 UTC
Labels: Couldn't reproduce, UnderInvestigation
