### ISSUE TITLE
Not able to create the project properly

### ISSUE THREAD

**Issue by kaushikmaji** [microsoft/AzureDevOpsDemoGenerator#228] opened 2020-04-09 12:01 UTC
The template breaks and is not able to create the project with board items and pipeline. While continuing to learn via az400 learning paths, after last module, I deleted the earlier project and now I can not create a new one with this error:

> Error while creating build definition: Unable to configure a service on the selected GitHub repository. This is likely caused by not having the necessary permission to manage hooks for the selected repository.

**Comment by aksh-h** [comment] 2020-04-13 06:32
@kaushikmaji could you please let us know which project you were trying to create

**Comment by kaushikmaji** [comment] 2020-04-13 19:33
@aksh-h: I was using template "Run quality tests in your build pipeline using Azure Pipelines" to create the project where I was getting the reported error

**Comment by aksh-h** [comment] 2020-04-14 11:21
@kaushikmaji  thank your for reporting. Our team is looking into this.

**Comment by aksh-h** [comment] 2020-04-15 05:11
@kaushikmaji we could not reproduce the issue. We would recommend you to try again in our preview [environment](https://demogen-code.azurewebsites.net) and let us know your feedback.

**Comment by aksh-h** [comment] 2020-04-17 11:51
@kaushikmaji we are closing the issue, if the issue still persists you can reopen the same or report new

**Closed by aksh-h** 2020-04-17 11:51 UTC
Labels: UnderInvestigation, needMoreInfo

**Comment by kaushikmaji** [comment] 2020-04-17 12:03
Sure Akshay, thanks. In case I face this issue again, I will capture and
share more details.

**Comment by aksh-h** [comment] 2020-04-17 12:04
Sure, Thank you @kaushikmaji

**Comment by mattcowen** [comment] 2020-12-16 09:26
i had the same issue in the demo generator however using the preview environment worked
