### ISSUE TITLE
Unable to create new template  Error while querying work items: VS403474

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [microsoft/AzureDevOpsDemoGenerator#186] opened 2019-10-24 13:52 UTC
So I am having frustrations creating a template.

![image](https://user-images.githubusercontent.com/6729780/67491535-00fd9e00-f66d-11e9-884d-3a066269c2cf.png)

Getting this error

Error while querying work items: VS403474: You requested 424 work items which exceeds the limit of 200
Error while querying work items: VS403474: You requested 415 work items which exceeds the limit of 200

Whilst the project has 0 work items

![image](https://user-images.githubusercontent.com/6729780/67492065-cba58000-f66d-11e9-9751-07e4d5afbcbe.png)

[AB#3616](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3616)

**Comment by Nullh** [comment] 2019-10-24 14:01
When I do this (colleague of Rob's) 
![image](https://user-images.githubusercontent.com/2921221/67492974-2390b680-f66f-11e9-8baf-471a27872b6e.png)

**Comment by aksh-h** [comment] 2019-10-25 05:28
@SQLDBAWithABeard thanks for reporting. We will inspect this. Meanwhile, Template Builder has some limitations which it can handle up to 200 work items of a type. If it exceeds, this would be expected error.

**Comment by SQLDBAWithABeard** [comment] 2019-10-25 07:29
@aksh-h Excellent, it was very strange as there were no work items in the Project as it is a brand new template Project, I had hit that earlier when I used a project with many work items (which is why this is an empty one!)

**Comment by aksh-h** [comment] 2019-10-25 07:36
@SQLDBAWithABeard we suspect this is returning from API end. If this is the case we will check with product team and get back to you.

**Comment by SQLDBAWithABeard** [comment] 2019-10-25 07:39
Thank you :-)

**Comment by aksh-h** [comment] 2019-11-08 05:46
@SQLDBAWithABeard Area you still facing the same issue?

**Comment by SQLDBAWithABeard** [comment] 2019-11-11 07:56
@aksh-h I will let you know when I am back at my client this week

**Comment by dmckinstry** [comment] 2019-12-17 12:27
HI @SQLDBAWithABeard  - Any update?  Aksh-h and I are doing routine maintenance and wanted to see if this is still causing an issues.  Thanks!

**Comment by tolgakarakurt** [comment] 2020-01-08 16:31
I have encountered the same error: 
Error while querying work items: **VS403474**: You requested 480 work items which exceeds the limit of 200
It has just started today. Maybe it is caused by recent intense usage. Looking for an immediate help on this. Thanks!
![image](https://user-images.githubusercontent.com/36911841/71996121-a99db180-3209-11ea-95cc-bc47134bb7fa.png)

**Comment by aksh-h** [comment] 2020-01-16 05:13
We believe this issue is no more exist. Hence closing the issue. You can reopen this anytime.

**Comment by Nullh** [comment] 2020-01-20 14:13
Looks like this is still an issue. 
![image](https://user-images.githubusercontent.com/2921221/72732880-a18d2c80-3b8e-11ea-8f04-61fd1b006f07.png)
![image](https://user-images.githubusercontent.com/2921221/72732865-96d29780-3b8e-11ea-98a1-3e86b8c53e32.png)

One other thing I've noticed, generating a template from any project within the same organization returns the same error.

**Comment by aksh-h** [comment] 2020-01-21 05:49
@Nullh this looks like API issue. While querying the work items, whatever response is coming from the API, the application is returning to user. @dmckinstry  and I will check this with the product team and get back to you.

**Comment by tasb** [comment] 2020-05-29 18:49
I'm getting the same error:
![image](https://user-images.githubusercontent.com/415105/83294514-5393cf80-a1e5-11ea-8041-59aa5b74067b.png)

But on project:
![image](https://user-images.githubusercontent.com/415105/83294585-70300780-a1e5-11ea-9421-8036e63c9e38.png)

**Comment by dmckinstry** [comment] 2020-05-31 20:09
Thanks all.  I want to make sure everyone understands.  The 200 limit is related to a limitation in the Azure DevOps API where we're limited to 200 work items without implementing paging (which we have considered out-of-scope).  We would consider accepting PRs if anyone is interested in implementing paging to get past the 200 work item limit, but we don't have any plans for change this ourselves.  Akshay has published a list of known limitations here: <https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md>

**Comment by DevOps-Travis** [comment] 2020-06-11 14:52
This error occurs when creating a template based off a brand new new project with no work items in a brand new org as well. The resulting template does import successfully.

_Selected Project: Template,   Process Template: Agile (system)
 Teams: 1
 Iteration: 1
Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Invalid URI: The Uri string is too long.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Invalid URI: The Uri string is too long.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Invalid URI: The Uri string is too long.

Error while querying work items: Object reference not set to an instance of an object.

Error while querying work items: Invalid URI: The Uri string is too long.

Error while querying work items: VS403474: You requested 222 work items which exceeds the limit of 200

Error while querying work items: VS403474: You requested 222 work items which exceeds the limit of 200_

**Comment by dmckinstry** [comment] 2020-06-12 01:18
@DevOps-Travis  - Do you think this issue is related to the original opened last October?  We'd already closed this issue and it may get lost.  If you think it is related, let me know and I'll reopen it.  Otherwise, can you copy/pasted with any other details into a new issue?  Thank you!

**Comment by chuckish** [comment] 2021-02-16 15:53
As of 2/16/2021, what has been described above has not been resolved.  Using the AzureDevOpsDemoGenerator tool, I get the VS403474 error when trying to create a template.  In my case, my project had less than 60 total work items, far below the 200 limit.  This tool could be enormously helpful if it would work properly.  Please advise as to what can be done to resolve this error.

**Comment by sjoshi077** [comment] 2021-03-09 16:09
The issue still persists, I am trying on a brand new organization, only created the project & trying to create the template but still it's failing with the same error 

@dmckinstry @aksh-h 

![image](https://user-images.githubusercontent.com/40919928/110501067-d2784a00-811f-11eb-8527-e988a8ad8f74.png)

**Comment by sjoshi077** [comment] 2021-03-09 17:45
@aksh-h, can you please try in your personal lab by creating a new organization & then a new project. try the azuredemogenerator  to create the template, if you didn't receive the error then I can grant access to you

@dmckinstry thanks for the quick response.

**Comment by aksh-h** [comment] 2021-03-10 03:49
> Hi all... Our problem is that we've been unable to reproduce the symptoms. It seems to follow certain people or template projects. But I have a proposal...
> 
> @aksh-h ... If someone had a template project that consistently failed with the reported issue and they granted access, could you effectively troubleshoot?
> 
> And if so, is someone on this issue willing to grant access to Akshay?

@dmckinstry since I couldn't reproduce this, its good idea to debug in users organization. Let me if @sjoshi077 can grant access to h.akshay@outlook.com

**Comment by aksh-h** [comment] 2021-03-10 05:40
@sjoshi077 can you please try it in our [beta](https://azuredevopsdemogenerator-beta.azurewebsites.net/) slot 
if the same issue persists, we can debug it in your environment.

**Comment by sjoshi077** [comment] 2021-03-10 10:25
> @sjoshi077 can you please try it in our [beta](https://azuredevopsdemogenerator-beta.azurewebsites.net/) slot
> if the same issue persists, we can debug it in your environment.

@aksh-h i am able to build the template in beta version but when i try to build the same in normal it failing to do so..

**Comment by aksh-h** [comment] 2021-03-10 10:30
is the issue still persist in [production](https://azuredevopsdemogenerator.azurewebsites.net/)?

**Comment by tinylabspace** [comment] 2021-03-10 13:29
This has been a roadblock for me as well. I just tried the production link and encountered the errors with an org with just one project and 0 work items. 

Selected Project: Project1,   Process Template: Scrum (system)
 Teams: 1
 Iteration: 6
Error while querying work items: VS403474: You requested 568 work items which exceeds the limit of 200
Error while querying work items: VS403474: You requested 568 work items which exceeds the limit of 200
Error while querying work items: VS403474: You requested 568 work items which exceeds the limit of 200
...
...

I tried the beta link above targeting the same org and project and it completed with no errors!

Selected Project: Project1,   Process Template: Scrum (system)
 Teams: 1
 Iteration: 6

I could provide access to that org/project if it was useful, I created it fresh a while back as a troubleshooting step for this myself.

**Comment by aksh-h** [comment] 2021-03-10 15:12
@tinylabspace  can you give a try in [beta](https://azuredevopsdemogenerator-beta.azurewebsites.net/) and let us know if you are facing the same?

**Comment by aksh-h** [comment] 2021-03-15 08:43
@tinylabspace could you please try out in [prod](https://azuredevopsdemogenerator.azurewebsites.net/)? let us know your feedback.

**Closed** 2021-05-27 03:25 UTC

**Comment by gidziu** [comment] 2021-06-18 09:13
did anyone resolve this VS403474 issue?
