### ISSUE TITLE
Templates do not work

### ISSUE THREAD

**Issue by crgarcia12** [microsoft/AzureDevOpsDemoGenerator#194] opened 2019-11-12 23:25 UTC
Today I created 5 different projects and the only one that worked out of the box was Hotel360. Contoso Air, MyHealth and PartsUnlimited faild with weird errors at build or release time.

Please test the templates :)

**Comment by aksh-h** [comment] 2019-11-13 05:38
@crgarcia12 could you please provide more info like which org you have used or what error you have received, we will investigate it.

**Comment by crgarcia12** [comment] 2019-11-13 09:14
Sure! This one for example: 
https://dev.azure.com/crgarcia/MyHealthClinic/_build/results?buildId=15

PS: The devops demo generator is the best thing that have been built in the last 5 years :)

**Comment by aksh-h** [comment] 2019-11-14 05:44
Thank you for more information.
Sorry we could not reproduce this, this might be an intermittent issue. We request you to retry. If the issue persists please share error details.

**Comment by crgarcia12** [comment] 2019-11-15 17:28
Hi @aksh-h , if you give me your email i can add you to my DevOps repository

**Comment by Scriptwarrior1027** [comment] 2020-01-02 19:58
I attempted use the MyHealth project and i can't get it to build either.

**Comment by dmckinstry** [comment] 2020-01-03 16:14
@Scriptwarrior1027 - I'm seeing the following in the npm install in my logs.  Can you confirm that it is the same issue?  @aksh-h - Is this a problem owned on the DemoGen side or the labs side?  Can you help?

24168 error errno 1

24169 error MyHealth.Web@1.0.0 postinstall: bower install --config.interactive=false & gulp

24169 error Exit status 1

24170 error Failed at the MyHealth.Web@1.0.0 postinstall script.

24170 error This is probably not a problem with npm. There is likely additional logging output above.

24171 verbose exit [ 1, true ]

    at Module.load (internal/modules/cjs/loader.js:815:32)

    at Function.Module._load (internal/modules/cjs/loader.js:727:14)

    at Module.require (internal/modules/cjs/loader.js:852:19)

    at require (internal/modules/cjs/helpers.js:74:18)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! MyHealth.Web@1.0.0 postinstall: bower install --config.interactive=false & gulp

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the MyHealth.Web@1.0.0 postinstall script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Scriptwarrior1027** [comment] 2020-01-03 21:50
Yes that is the same issue i am seeing

**Comment by aksh-h** [comment] 2020-01-06 05:17
@sriramdasbalaji can you please verify this?

**Comment by aksh-h** [comment] 2020-01-09 14:09
fixed issue with MHC pipeline and will be available in prod soon

**Comment by aksh-h** [comment] 2020-01-10 06:03
Merged and released to prod. Hence closing the issue

**Closed by aksh-h** 2020-01-10 06:03 UTC
